logging:
  level:
    root: WARN
    "[com.example.demo]": DEBUG

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:demo
    driver-class-name: org.h2.Driver
    username: sa
    password:
